name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ssn-server

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install

      - name: Test
        working-directory: ${{ env.working-directory }}
        run: npm run test
