name: matrix-profile-service CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./matrix-profile-service

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Checkout
        uses: ./matrix-profile-service
        env:
          CI: true
